### ISSUE TITLE
Create policy for synchronization of PDF and .owl file/OLS exposure.

### ISSUE THREAD

**Issue by luciansmith** [probonto/ontology#2]
As an example, I chose the 'power normal' distribution from the 2.5 specification, but when I went to look it up in the .owl file itself (https://github.com/probonto/ontology/blob/master/probonto4ols.owl), I was not able to find it--a text search of the file does not find the word 'power' anywhere.  Is the .owl file not updated to version 2.5?  Do the .owl file and the PDF not get updated at the same time?

**Comment by pgrenon** [comment]
Currently, the OWL file is that corresponding to version 2 and not 2.5 so you will not find Power Normal as it is not defined in 2. 

Technically speaking, everything is in a primary model and both elements of the PDF (which is fine tuned manually) and OWL are derived from it through similar but independent processes. 

It seems an issue is also that there is no policy as to which revision level makes it to the OLS exposure. Thanks for pointing this out, the issue remains open until there is a policy and the OWL version is comliant with it.

**Comment by luciansmith** [comment]
Sounds good!  No rush on this; I was just searching around and was confused by the inconsistency.  Thanks for the reply!

**Comment by pgrenon** [comment]
- probonto-v2.5.owl now uploaded in release
- 'power normal' is known as "Power-Normal 1", codename: PowerNormal1, URI: http://www.probonto.org/ontology#PROB_k0001230
- probonto-v2.5.owl cloned to probonto4ols.owl
- README.md is now verbose. It indicates the discrepancy of processes in generating PDF documents and OWL files. It can be interpreted as saying there is no coupling strategy. The README.md also refers to OLS and stipulates that "This file is updated with minor revisions of the OWL implementation of ProbOnto." 

It seems to me a good enough trade off for the purpose and I'm closing this issue. However, if you feel like the 'policy' is problematic, inadequate or requires more work, please open a new one.

**Comment by luciansmith** [comment]
Sounds great!  Thanks for the updates.
